### ISSUE TITLE
++ -- 等一元运算符无法正常运行

### ISSUE THREAD

**Issue by DQinYuan** [alibaba/QLExpress#108]
比如：

```java
	@Test
	public void forTest() throws Exception {
		String express = "4++";
		ExpressRunner runner = new ExpressRunner(false,true);

		DefaultContext<String, Object> context = new DefaultContext<String, Object>();
		Object r = runner.execute(express, context, null, false, true);
		System.out.println(r);
	}
```

运行报错：

```
com.ql.util.express.exception.QLBizException: run QlExpress Exception at line 1 :

	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:52)
	at com.ql.util.express.InstructionSet.executeInnerOrigiInstruction(InstructionSet.java:217)
	at com.ql.util.express.InstructionSet.excute(InstructionSet.java:185)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:65)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:52)
	at com.ql.util.express.InstructionSetRunner.executeOuter(InstructionSetRunner.java:23)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:613)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:581)
	at com.ql.util.express.test.ForFlowFunctionTest.forTest(ForFlowFunctionTest.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:130)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.RuntimeException: 必须在子类中实现此方法
	at com.ql.util.express.OperateData.setObject(OperateData.java:61)
	at com.ql.util.express.instruction.op.OperatorDoubleAddReduce.executeInner(OperatorDoubleAddReduce.java:24)
	at com.ql.util.express.instruction.op.OperatorBase.execute(OperatorBase.java:68)
	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:46)
	... 29 more
```

**Comment by DQinYuan** [comment]
常量本来就不能加在一元运算符上，乌龙问题，关闭
