### ISSUE TITLE
无法在自定义函数中再次调用引擎

### ISSUE THREAD

**Issue by DQinYuan** [alibaba/QLExpress#122]
我想实现一个 eval 函数，在 eval 中再次再次调用引擎执行传入的代码片段，如下：

```java
    @Test
    public void evalTestFail() throws Exception {
        String evalExpress = "eval('1+1')";
        final ExpressRunner runner = new ExpressRunner(false,true);
        runner.addFunction("eval", new OperatorBase() {
            @Override
            public OperateData executeInner(InstructionSetContext parent, ArraySwap list) throws Exception {
                Object res = runner.execute(list.get(0).toString(), parent,
                        null, false, true);
                return new OperateData(res, res.getClass());
            }
        });

        Object res = runner.execute(evalExpress, new DefaultContext<String, Object>(), null,
                false, true);
        assertEquals(2, res);
    }
```

最后引擎报错：

```
com.ql.util.express.exception.QLBizException: run QlExpress Exception at line -1 :

	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:52)
	at com.ql.util.express.InstructionSet.executeInnerOrigiInstruction(InstructionSet.java:217)
	at com.ql.util.express.InstructionSet.excute(InstructionSet.java:185)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:64)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:51)
	at com.ql.util.express.InstructionSetRunner.executeOuter(InstructionSetRunner.java:23)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:613)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:581)
	at com.ql.util.express.bugfix.EvalTest.evalTestFail(EvalTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:130)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.NullPointerException
	at com.ql.util.express.bugfix.EvalTest$1.executeInner(EvalTest.java:23)
	at com.ql.util.express.instruction.op.OperatorBase.execute(OperatorBase.java:68)
	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:46)
	... 29 more


Process finished with exit code 255
```

**Comment by DQinYuan** [comment]
这个问题我已经找到并且修复了，是因为嵌套执行脚本退出时，虚拟机指针被重置，导致执行错误。需要这个特性的可以合一下我的 [PR](https://github.com/alibaba/QLExpress/pull/123)，然后需要嵌套执行脚本时调用 com.ql.util.express.ExpressRunner#eval 即可

**Comment by baoxingjie** [comment]
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md
使用3.2.6 版本
