### ISSUE TITLE
嵌套事物公式引擎空指针异常

### ISSUE THREAD

**Issue by icesugar** [alibaba/QLExpress#133]
公式里 写for循环，循环过程中某一个函数发生嵌套事物抛出的异常，导致这里空指针。现在规避方式就是不用循环，每次执行公式只处理一条的信息，返回值为空就判定执行失败。
```
OperatorSelfDefineServiceFunction.executeInner(OperatorSelfDefineServiceFunction.java:76)
```

```
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor451.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ql.util.express.instruction.op.OperatorSelfDefineServiceFunction.executeInner(OperatorSelfDefineServiceFunction.java:76)
	at com.ql.util.express.instruction.op.OperatorBase.execute(OperatorBase.java:68)
	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:46)
	... 32 common frames omitted
Caused by: org.springframework.transaction.UnexpectedRollbackException: Transaction rolled back because it has been marked as rollback-only
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(
```

**Comment by baoxingjie** [comment]
麻烦给出一个case，目前嵌套调用，runner需要不同的实例

**Comment by baoxingjie** [comment]
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md
使用3.2.6 ，runner重入问题已经解决
