### ISSUE TITLE
express直接调用ProcessBuilder.start()报错

### ISSUE THREAD

**Issue by yuanjunxiaoli** [alibaba/QLExpress#140]
代码：
	public void MultipleStatementsTest() throws Exception {
		ExpressRunner runner = new ExpressRunner(false, true);
		DefaultContext context = new DefaultContext();
		QLExpressRunStrategy.setForbiddenInvokeSecurityRiskMethods(false);
		String expressString = "ProcessBuilder processBuilder = new ProcessBuilder(\"C:/Windows/System32/cmd.exe\", \"/c calc\");"
				+ "Process process = processBuilder.start();";
		InstructionSet instructionSet = runner.parseInstructionSet(expressString);
		Object r = runner.execute(expressString, context, null, true, true);
		System.out.println(r);
	}

报错信息：
com.ql.util.express.exception.QLBizException: run QlExpress Exception at line 1 :

	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:52)
	at com.ql.util.express.InstructionSet.executeInnerOrigiInstruction(InstructionSet.java:217)
	at com.ql.util.express.InstructionSet.excute(InstructionSet.java:185)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:64)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:51)
	at com.ql.util.express.InstructionSetRunner.executeOuter(InstructionSetRunner.java:23)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:613)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:581)
	at com.ql.util.express.test.SecurityResearchTest.MultipleStatementsTest(SecurityResearchTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:130)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.ql.util.express.ExpressUtil.findConstructorWithCache(ExpressUtil.java:277)
	at com.ql.util.express.instruction.op.OperatorNew.executeInner(OperatorNew.java:42)
	at com.ql.util.express.instruction.op.OperatorBase.execute(OperatorBase.java:68)
	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:46)
	... 29 more

**Comment by yuanjunxiaoli** [comment]
wrong
