### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by uuxii** [alibaba/QLExpress#189]
public static void main(String[] args) {
		//初始化脚本执行器
		ExpressRunner runner = new ExpressRunner();
		//获取执行器上下文对象
		DefaultContext<String, Object> reactContext = new DefaultContext<>();
		reactContext.put("{条件A}",true);
		reactContext.put("{条件B}",false);
		boolean result = (Boolean) runner.execute("{条件A} || {条件B}" ,reactContext, null, true, false);
		System.out.println(result);
	}

报错内容：

Exception in thread "main" com.ql.util.express.exception.QLCompileException: 还有单词没有完成语法匹配：3[||:line=1,col=7] 之后的单词 
{条件A} || {条件B}
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:401)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:355)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:329)
	at com.ql.util.express.ExpressRunner.parseInstructionSet(ExpressRunner.java:724)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:612)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:589)
	at cc.vker.SqliteTestApplicationTests.main(SqliteTestApplicationTests.java:27)

是在整不明白了~~~~~逻辑中必须带有花括号，是花括号有特殊含义么？可是转义了依旧报错

**Comment by pymBupt** [comment]
当前版本不支持，目前在规划新版本，计划新版本支持下，可加wx（pymbupt）保持联系
