### ISSUE TITLE
Caused by: java.lang.StackOverflowError，ExpressRunner初始化报错

### ISSUE THREAD

**Issue by LeeLoveC** [alibaba/QLExpress#218]
JVM配置从2G 测试到6G 都有问题。 代码运行在容器上报错，本地无法复现

    private static volatile ExpressRunner runner;
    public static ExpressRunner newInstance() {
        if (Objects.nonNull(runner)) {
            return runner;
        }
        if (Objects.isNull(runner)) {
            synchronized (CalculateWrapper.class) {
                if (Objects.isNull(runner)) {
                    return new ExpressRunner(true, false);
                }
            }
        }
        return runner;
    }

Caused by: java.lang.StackOverflowError: null
        at java.util.ArrayList.toArray(ArrayList.java:411)
        at com.ql.util.express.parse.ExpressNode.getChildrenArray(ExpressNode.java:181)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:20)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)
        at com.ql.util.express.ExpressRunner.createInstructionSetPrivate(ExpressRunner.java:760)
        at com.ql.util.express.instruction.OperatorInstructionFactory.createInstruction(OperatorInstructionFactory.java:24)

**Comment by LeeLoveC** [comment]
POM配置
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>QLExpress</artifactId>
            <version>3.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-lang</groupId>
                    <artifactId>commons-lang</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by LeeLoveC** [comment]
POM配置，jdk 1.8
> <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>QLExpress</artifactId>
            <version>3.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-lang</groupId>
                    <artifactId>commons-lang</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by taokan** [comment]
方便加我微信号吗，tkk33362，了解下细节

**Comment by DQinYuan** [comment]
提问者暂未提供进一步信息，先 close
