### ISSUE TITLE
能否支持嵌套的三目运算

### ISSUE THREAD

**Issue by z610zhangzhihao** [alibaba/QLExpress#219]
a <=3?100:a<=8?200:300
报错信息：
17:30:31.680 [main] ERROR com.topideal.supplychain.pps.engine.QLExpressEngine - 表达式执行错误：a <=3?100:a<=8?200:300程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配致[0:8]
com.ql.util.express.exception.QLCompileException: 程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配致[0:8]
	at com.ql.util.express.match.QLPattern.findMatchStatement(QLPattern.java:49)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:403)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:361)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:334)
	at com.ql.util.express.ExpressRunner.parseInstructionSet(ExpressRunner.java:700)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:656)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:632)
	at com.topideal.supplychain.pps.engine.QLExpressEngine.exec(QLExpressEngine.java:39)
	at QlExpressTest.expressTest(QlExpressTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by DQinYuan** [comment]
a <=3?100:(a<=8?200:300)

加上括号即可。

**Comment by DQinYuan** [comment]
我们目前在开发的新版本 QLExpress4，会支持你所提的那种省略括号的写法。有兴趣的话我们可以加个微信更深入地聊一聊使用场景和需求，微信号可以发我邮箱 dqydqyuan@gmail.com
