### ISSUE TITLE
Caused by: java.lang.StackOverflowError 

### ISSUE THREAD

**Issue by Fyee** [alibaba/QLExpress#270]
是不是因为公示过长就会这样？
依赖
```xml
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>QLExpress</artifactId>
            <version>3.3.1</version>
        </dependency>
```

报错信息如下：
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.StackOverflowError
	at com.ql.util.express.parse.NodeTypeManager.findNodeType(NodeTypeManager.java:10)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:63)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:187)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:130)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:86)
	at com.ql.util.express.match.QLPattern.findMatchStatement(QLPattern.java:28)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:400)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:358)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:331)
	at com.ql.util.express.ExpressRunner.parseInstructionSet(ExpressRunner.java:688)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:645)

**Comment by DQinYuan** [comment]
具体公式和 jvm 栈大小发出来看看呢？QLExpress 目前在公式语法层次太深的情况下，如果栈空间太小是有溢出问题

**Comment by DQinYuan** [comment]
QLExpress4 将会解决栈的问题。有兴趣可以把微信发邮箱
qinyuan.dqy@alibaba-inc.com
我们更进一步交流
