### ISSUE TITLE
||运算符无法设置别名OR，不设置又提示找不到运算符

### ISSUE THREAD

**Issue by moyispace** [alibaba/QLExpress#319]
// 设置|| 运算别名 为OR 
ExpressRunner runner = new ExpressRunner();
DefaultContext<String, Object> userExpressContext = new DefaultContext<String, Object>();
runner.addOperatorWithAlias("OR", "or", null);
String expression = "1==1 OR 2==3";
 //执行表达式
Object execute = runner.execute(expression, userExpressContext, null, false, true);

错误信息
Exception in thread "main" java.lang.RuntimeException: 节点类型定义重复:OR 定义1=OR:TYPE=WORDDEF,DEFINE=|| 定义2=OR:TYPE=KEYWORD,REAL=||
	at com.ql.util.express.parse.NodeTypeManager.createNodeType(NodeTypeManager.java:92)
	at com.ql.util.express.parse.NodeTypeManager.addOperatorWithRealNodeType(NodeTypeManager.java:121)
	at com.ql.util.express.ExpressRunner.addOperatorWithAlias(ExpressRunner.java:450)

//不设置别名
ExpressRunner runner = new ExpressRunner();
DefaultContext<String, Object> userExpressContext = new DefaultContext<String, Object>();
String expression = "1==1 OR 2==3";
 //执行表达式
Object execute = runner.execute(expression, userExpressContext, null, false, true);

错误信息
Exception in thread "main" java.lang.Exception: 程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配致[0:2]
	at com.ql.util.express.match.QLPattern.findMatchStatement(QLPattern.java:21)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:343)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:310)
	at com.ql.util.express.ExpressRunner.parseInstructionSet(ExpressRunner.java:656)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:568)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:538)

如果想给|| 设置别名OR该如何操作呢？

**Comment by taokan** [comment]
系统默认内置的“or”，不需要执行addOperatorWithAlias

**Comment by moyispace** [comment]
我明白您说的，但是业务方统一规定用大写 OR

**Comment by DQinYuan** [comment]
@taokan  我仔细看了下，这确实 QL3 内部的一个 bug。
内置的 OR 节点仅仅是为了引用而存在的，却把 OR 这个名字给占了，下面这样改就行了

<img width="1009" alt="image" src="https://github.com/alibaba/QLExpress/assets/23725000/bbf51593-0b66-441e-844b-bec632d4cf37">

<img width="882" alt="image" src="https://github.com/alibaba/QLExpress/assets/23725000/0d62d4f7-f4b9-4d9e-af47-a7f6f0d6c83d">

将内置的 OR 节点名字改成 OR_INNER 即可

**Comment by taokan** [comment]
确实可以，需要保留qhttps://github.com/alibaba/QLExpress/pull/324
