### ISSUE TITLE
关于扩展函数IF除数为0的问题

### ISSUE THREAD

**Issue by zimo1213** [alibaba/QLExpress#333]
我扩展了IF函数
```
@Alias("IF")
@Component
public class IfFunction extends Operator implements QleStandardFunction {

    @Override
    public Object executeInner(Object[] parameters) throws Exception {
        Object condition = parameters[0];
        if (!(condition instanceof Boolean)) {
            throw new Exception();
        }
        if ((Boolean) condition) {
            return parameters[1];
        }
        if (parameters.length > 2) {
            return parameters[2];
        }
        return false;
    }
}
```

当输入为`IF(b==0, 0, a/b)`

```
QLExpressRunStrategy.setSandBoxMode(true);

ExpressRunner runner = new ExpressRunner();
runner.setIgnoreConstChar(true);
runner.addFunction("IF", new IfFunction());

DefaultContext<String, Object> context = new DefaultContext<String, Object>();
context.put("a", 1);
context.put("b", 0);
String express = "IF(b==0, 0, a/b)";
Object r = runner.execute(express, context, null, true, false);

```

会触发错误  `/ by zero`

```
com.ql.util.express.exception.QLBizException: run QlExpress Exception at line 1 :

	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:38)
	at com.ql.util.express.InstructionSet.executeInnerOriginalInstruction(InstructionSet.java:200)
	at com.ql.util.express.InstructionSet.execute(InstructionSet.java:164)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:64)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:55)
	at com.ql.util.express.InstructionSetRunner.executeOuter(InstructionSetRunner.java:19)
	at com.ql.util.express.ExpressRunner.executeReentrant(ExpressRunner.java:655)
	at com.ql.util.express.ExpressRunner.executeInner(ExpressRunner.java:641)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:629)
	at com.dingtalk.hrm.salary.qle.calculate.CalculationQleRunnerFactoryTest.b(CalculationQleRunnerFactoryTest.groovy:46)
Caused by: java.lang.ArithmeticException: / by zero
	at com.ql.util.express.NormalNumberOperator.divideNormal(OperatorOfNumber.java:333)
	at com.ql.util.express.OperatorOfNumber.divide(OperatorOfNumber.java:216)
	at com.ql.util.express.instruction.op.OperatorMultiplyDivide.executeInner(OperatorMultiplyDivide.java:23)
	at com.ql.util.express.instruction.op.OperatorMultiplyDivide.executeInner(OperatorMultiplyDivide.java:13)
	at com.ql.util.express.Operator.executeInner(Operator.java:26)
	at com.ql.util.express.instruction.op.OperatorBase.execute(OperatorBase.java:56)
	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:32)
	... 9 more

```

我尝试了 `QLambda`

```
@Alias("IF")
@Component
public class IfFunction extends Operator implements QleStandardFunction {

    @Override
    public Object executeInner(Object[] parameters) throws Exception {
        Object condition = parameters[0];
        if (!(condition instanceof Boolean)) {
            throw new Exception();
        }
        if ((Boolean) condition) {
            Object trueVale = parameters[1];
            if (trueVale instanceof QLambda) {
                return ((QLambda) trueVale).call();
            }
            return trueVale;
        }
        if (parameters.length > 2) {
            Object falseVale = parameters[2];
            if (falseVale instanceof QLambda) {
                return ((QLambda) falseVale).call();
            }
            return falseVale;
        }
        return false;
    }
}
```

再次输入`IF(b==0, 0, ()-> a/b)`

可以得到正确结果 

有什么更好的方式可以处理这个问题呢

**Comment by DQinYuan** [comment]
这里看起来想要的是控制流，而不是值传递。目前除了 lambda 以外确实没有更好的解法。可以给点建议

**Comment by zimo1213** [comment]
> 这里看起来想要的是控制流，而不是值传递。目前除了 lambda 以外确实没有更好的解法。可以给点建议

已解决，得力于扩展函数的能力，在此基础上扩展了除法函数`DIVIDE(被除数, 除数, 除数为0的默认值)`

现状
```
日工资 = 
IF(
    #排班天数#  == 0,
    100,
    ()-> #基本工资# / #排班天数# 
)
```

扩展函数后
```
日工资 = 
DIVIDE(
    #基本工资#, 
    #排班天数#,
    100
)
```

已经线上试运行了一段时间，客户的接受程度很高
