### ISSUE TITLE
长脚本的文本解析报错：程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配至[0:234]

### ISSUE THREAD

**Issue by SmileAndWind** [alibaba/QLExpress#359]
QLExpress版本：3.2.5

##实例代码
import com.ql.util.express.DefaultContext;
import com.ql.util.express.ExpressRunner;

public class Test {

    public static void main(String[] args) throws Exception {
        ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context2 = new DefaultContext<String, Object>();
        context2.put("skuId", 123L);
        context2.put("firstPurchase", 0);
        String express = "if ((20514311 == skuId || 20518744 == skuId || 20519163 == skuId || 20519205 == skuId || 20519977 == skuId || " +
                "20520031 == skuId || 20520032 == skuId || 20520199 == skuId || 20525491 == skuId || 20518747 == skuId || 20526975 == skuId " +
                "|| 20527011 == skuId || 20527686 == skuId || 20527948 == skuId || 20531085 == skuId || 20531084 == skuId || 20537219 == skuId" +
                " || 20537309 == skuId || 20540067 == skuId || 20540066 == skuId || 20542246 == skuId || 20542007 == skuId || 20543461 == skuId" +
                " || 20544353 == skuId || 20545545 == skuId || 20545546 == skuId || 20549648 == skuId || 20549649 == skuId || 20550120 == skuId ||" +
                " 20552634 == skuId || 20552635 == skuId || 20517307 == skuId || 20519180 == skuId || 20527961 == skuId || 20531081 == skuId || 20517370 == skuId || 20543820 == skuId || 20543745 == skuId || 20544427 == skuId || 20544176 == skuId || 20542834 == skuId || 20543360 == skuId || 20543400 == skuId || 20545639 == skuId || 20545638 == skuId || 20550934 == skuId || " +
                "20550935 == skuId || 20551451 == skuId || 20551353 == skuId || 20554134 == skuId || 20554034 == skuId || 20558550 == skuId || 20558473 == skuId || 20559600 == skuId" +
                " || 20559548 == skuId || 20559796 == skuId || 20559797 == skuId || 20559855 == skuId || == skuId || 20560253 == skuId || 20560198 == skuId) && (1 == firstPurchase)) {\n" +
                "\treturn true;\n" +
                "} else {\n" +
                "\treturn false;\n" +
                "}";
        Object r = runner.execute(express, context2, null, true, false);
        System.out.println(r);
    }
}

报错：
Exception in thread "main" com.ql.util.express.exception.QLCompileException: 程序错误，不满足语法规范，没有匹配到合适的语法,最大匹配至[0:234]
	at com.ql.util.express.match.QLPattern.findMatchStatement(QLPattern.java:30)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:409)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:367)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:340)
	at com.ql.util.express.ExpressRunner.parseInstructionSet(ExpressRunner.java:678)
	at com.ql.util.express.ExpressRunner.lambda$getInstructionSetFromLocalCache$2(ExpressRunner.java:710)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.ql.util.express.ExpressRunner.getInstructionSetFromLocalCache(ExpressRunner.java:714)
	at com.ql.util.express.ExpressRunner.executeInner(ExpressRunner.java:636)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:629)

目前怀疑是脚本文本太长导致的报错，麻烦看看是否是这个问题

**Comment by SmileAndWind** [comment]
脚本格式问题，无需处理
