### ISSUE TITLE
发现了个bug

### ISSUE THREAD

**Issue by Luyu05** [alibaba/QLExpress#37]
```java
public static void main(String[] args) throws Exception {
        ExpressRunner runner = new ExpressRunner();
        DefaultContext<String, Object> context = new DefaultContext<String, Object>();
        String express = "part = \"1@2@3\".split(\"@\");\n" +
                "Integer.valueOf(part[2]);";
        runner.execute(express, context, null, true, false);
}
```
执行这段代码会报这个错误
```java
Caused by: java.lang.Exception: 没有找到java.lang.Class的方法：valueOf([Ljava.lang.String;)
	at com.ql.util.express.instruction.op.OperatorMethod.executeInner(OperatorMethod.java:96)
	at com.ql.util.express.instruction.op.OperatorBase.execute(OperatorBase.java:67)
	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:44)
	... 8 more
```
把express的内容改为
```java
part = "1@2@3".split("@");
str = part[2];
Integer.valueOf(str);
```
就可以了

**Comment by baoxingjie** [comment]
是的，目前在数组的识别上是有bug

**Comment by baoxingjie** [comment]
https://github.com/alibaba/QLExpress/blob/master/VERSIONS.md
使用3.2.5，类型识别上的bug已经修复
