### ISSUE TITLE
属性访问无法支持Builder模式的GetSet方法

### ISSUE THREAD

**Issue by jujusharp** [alibaba/QLExpress#50]
### 运行环境  
JDK 1.8
QLExpress 3.2.2
Windows 10

### 问题描述
当使用Builder模式的属性时, 系统无法正确读取属性值.  
#### 示例代码
```
public class ELDemoEntity {
    private String name;
    private Long id;
    public String getName() {
        return name;
    }
    public ELDemoEntity setName(String name) {
        this.name = name;
        return this;
    }
    public Long getId() {
        return id;
    }
    public ELDemoEntity setId(Long id) {
        this.id = id;
        return this;
    }
}

@Test
    public void test5() throws Exception {
        ExpressRunner runner = new ExpressRunner(true,true);
        String express = "if(demo.getId()==1)then{demo.id=2};return 0";
        System.out.println(express);

        IExpressContext<String,Object> expressContext = new DefaultContext<String,Object>();
        ELDemoEntity entity = new ELDemoEntity();
        entity.setId(1L).setName("zhangsan");
        expressContext.put("demo", entity);
        Object r = runner.execute(express,
                expressContext, null, false, false);
        System.out.println("r=" + r);
        System.out.println(entity.getId());
    }
```

####  错误的堆栈信息  
```
java.lang.Exception: run QlExpress Exception at line 1 :

	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:48)
	at com.ql.util.express.InstructionSet.executeInnerOrigiInstruction(InstructionSet.java:217)
	at com.ql.util.express.InstructionSet.excute(InstructionSet.java:183)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:59)
	at com.ql.util.express.InstructionSetRunner.execute(InstructionSetRunner.java:46)
	at com.ql.util.express.InstructionSetRunner.executeOuter(InstructionSetRunner.java:18)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:587)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:555)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
Caused by: java.lang.RuntimeException: 不能访问cn.loopcloud.ELDemoEntity@59d4cd39的property:id
	at com.ql.util.express.ExpressUtil.setProperty(ExpressUtil.java:587)
	at com.ql.util.express.instruction.opdata.OperateDataField.setObject(OperateDataField.java:108)
	at com.ql.util.express.instruction.op.OperatorEvaluate.executeInner(OperatorEvaluate.java:37)
	at com.ql.util.express.instruction.op.OperatorEvaluate.executeInner(OperatorEvaluate.java:18)
	at com.ql.util.express.instruction.op.OperatorBase.execute(OperatorBase.java:67)
	at com.ql.util.express.instruction.detail.InstructionOperator.execute(InstructionOperator.java:44)
	... 30 more
Caused by: java.lang.NoSuchMethodException: Property 'id' has no setter method in class 'class cn.loopcloud.ELDemoEntity'
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2084)
	at org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1903)
	at org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2010)
	at org.apache.commons.beanutils.PropertyUtils.setProperty(PropertyUtils.java:896)
	at com.ql.util.express.ExpressUtil.setProperty(ExpressUtil.java:584)
	... 35 more
```

### 建议方案
1. 能否将对象属性, 字段, 方法的操作抽象为接口并支持外部自定义, 这样, 能很方便的支持外部切换对象访问逻辑.
2. 是否有计划提供比apache beanutils更加高效的属性访问方式, 如字节码访问等, 以提升性能

**Comment by baoxingjie** [comment]
1、属性访问默认是beanutils 标准的的get，set方法，你这个case需要修改为

if(demo.getId()==1)then{demo.setId(2L)};return 0;

2、既然是脚本，瓶颈一般不会在beanutils这种工具类上，因为实际开销要比java调用高一个数量级以上。而且beanutils目前来说性能并不是特别差，底层也有方法缓存，其他的类似cglib 的 BeanCopier实际也有潜在的问题，比如属性不一致的处理等等。如果真的性能要求很高，通过脚本调用自己写的工具类来实现。
