### ISSUE TITLE
脚本中存在使用绑定的Java类方法时CacheObject不能序列化，无法放入RemoteCache

### ISSUE THREAD

**Issue by dragon0574** [alibaba/QLExpress#58]
* 需求
> 由于规则量巨大，7w多条逻辑运算规则，需要集群部署，使用自带的HashMap缓冲规则的指令集会重复占用较多的内存资源，故决定使用独立与应用之外的缓冲。
* 实现参考
> [QLExpress脚本语言技术讲解（6）-------QLExpress的缓存管理](https://blog.csdn.net/express_wind/article/details/84231213)
具体见播客里描述到的第三部分内容**3、独立于ExpressRunner的外部缓存处理器**
* 实现
> 基于Redis实现了一个`RedisExpressCacheRunner`外部缓冲管理器，脚本中不使用绑定的`java`类方法时，一切正常。
* 使用的版本
`3.2.0`
* 问题描述
> 当要执行的脚本中使用`addFunctionOfClassMethod`或者`addFunctionOfServiceMethod`绑定的java类方法时，对应的缓冲对象`CacheObject`是无法序列化的，会报错`java.io.NotSerializableException: java.lang.reflect.Method`。
* 报错代码：
> 使用QLExpress自带的LocalExpressCacheRunner来加载脚本放入缓冲，获取到CacheObject时，模拟Redis序列化的过程
```java
// 这个脚本序列化会报错
String ruleFormula="(IDX005=='负') && parseNum(IDX006)>1000";
// 这个脚本序列话就不会报错
// String ruleFormula="(IDX005=='负') ";
DefaultContext<String, Object> context = new DefaultContext<String, Object>();
context.put("IDX005", "负");
context.put("IDX006", "1800.94");
ExpressRunner runner = new ExpressRunner();
// 将字符串转为数字进入脚本逻辑判断
runner.addFunctionOfClassMethod("parseNum", BeanExample.class.getName(), 
        "parseStrToDouble", new String[] { "String" }, null);
ExpressRemoteCacheRunner cacheRunner = new LocalExpressCacheRunner(runner);
String expressString = "是否为真";
cacheRunner.loadCache(expressString, ruleFormula);
echo(cacheRunner.execute(expressString, context, null, false, false, null));
CacheObject cache = (CacheObject) cacheRunner.getCache(expressString);
echo(runner.execute(cache.getInstructionSet(), context, null, false, false, null));
// 测试CacheObject能否序列化
ByteArrayOutputStream byteStream = new ByteArrayOutputStream(1024);
ObjectOutputStream objectOutputStream = new ObjectOutputStream(byteStream);
try {
    objectOutputStream.writeObject(cache);
} catch (Exception e) {
    e.printStackTrace();
}
objectOutputStream.flush();
```
* 全量报错
> java.io.NotSerializableException: java.lang.reflect.Method
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.xxx.test.QLExpress.remote.TestQLExpress4RemoteCache.testExpress4RedisCache3Issues(TestQLExpress4RemoteCache.java:44)// 这儿已经是我的测试类了
* 问题理解
> 报错`java.io.NotSerializableException: java.lang.reflect.Method`，这个报错很常见，就是这个类没有实现序列化接口，但是这个类偏偏是` java.lang.reflect.Method`，这是在为难我胖虎，走入了死胡同，不知道该从哪个角度去解决处理这个问题，敬请帮忙查看，是框架本身的限制还是我使用的问题。
感谢感谢

**Comment by baoxingjie** [comment]
建议不要使用以下这种方式：
runner.addFunctionOfClassMethod("parseNum", BeanExample.class.getName(), 
        "parseStrToDouble", new String[] { "String" }, null);
否则会产生以下的指令集而无法序列化：OperatorSelfDefineClassFunction
public class OperatorSelfDefineClassFunction extends OperatorBase implements CanClone{

   Class<?>[] parameterClasses ;
   Class<?> operClass;
   Method method;
}

可以参考这种解决方案
```
public class MyOperator extends Operator {
    @Override
    public Object executeInner(Object[] list) throws Exception {
        return BeanExample.parseStrToDouble((String)list[0]);
    }
}
runner.addFunction("parseNum", new MyOperator());
```

**Comment by dragon0574** [comment]
感谢感谢，我太愚钝，理解不到位。
返回去看README里是有写的，但是为啥自己就不会去试试哩。
后期改版是我会尝试使用这种方式，现在项目已经上线了
