### ISSUE TITLE
对||操作设置别名(addOperatorWithAlias("或者","||","$1 或者 $2");)出现null异常，其他操作符对比没有发现

### ISSUE THREAD

**Issue by yanzhaohu** [alibaba/QLExpress#61]
测试代码和异常如下：
```
public void testOr(){
        String rule = "a||b";
        ExpressRunner runner = new ExpressRunner();
        runner.setShortCircuit(false);
        IExpressContext<String, Object> context =new DefaultContext<String, Object>();
        List<String> errorInfo = new ArrayList<String>();
        context.put("a",true);
        context.put("b",false);
        try {
            //runner.getOperatorFactory().getOperator("||").setErrorInfo("$1 || $2 ");
            runner.addOperatorWithAlias("或者","||","$1 或者 $2");
            Object  result =  runner.execute(rule, context, errorInfo, false, false);
            System.out.println(result);
            for(String error : errorInfo){
                System.out.println(error);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
```

异常信息：

```
java.lang.Exception: 不正确的类型：NULL
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:195)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:188)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:85)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:85)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:188)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:188)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:188)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:188)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:126)
	at com.ql.util.express.match.QLPattern.findMatchStatementWithAddRootOptimizeStack(QLPattern.java:85)
	at com.ql.util.express.match.QLPattern.findMatchStatement(QLPattern.java:26)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:392)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:354)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:328)
	at com.ql.util.express.ExpressRunner.parseInstructionSet(ExpressRunner.java:673)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:585)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:555)

```

通过跟踪发现：

com.ql.util.express.match.QLPattern的187行

for \(QLPatternNode item : pattern.children\) {

代码，pattern.children 有5条数据，前三条为null。
其他内置操作符可以设置别名操作正常，例如：
```
String rule = "a 或者 b";
        ExpressRunner runner = new ExpressRunner();
        runner.setShortCircuit(false);
        IExpressContext<String, Object> context =new DefaultContext<String, Object>();
        List<String> errorInfo = new ArrayList<String>();
        context.put("a",1);
        context.put("b",11);
        try {
            // runner.getOperatorFactory().getOperator("||").setErrorInfo("$1 或 $2 ");
            runner.addOperatorWithAlias("或者","<","$1 或者 $2");
            Object  result =  runner.execute(rule, context, errorInfo, true, false);
            System.out.println(result);
            for(String error : errorInfo){
                System.out.println(error);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
```

**Comment by baoxingjie** [comment]
|| 本身就是逻辑操作符，不能作为普通的二元操作

**Comment by yanzhaohu** [comment]
&&也是逻辑操作，可以设置别名，执行结果正确，||设置别名直接就会null异常
```String rule = "a 或者 b";
        ExpressRunner runner = new ExpressRunner();
        runner.setShortCircuit(false);
        IExpressContext<String, Object> context =new DefaultContext<String, Object>();
        List<String> errorInfo = new ArrayList<String>();
        context.put("a",true);
        context.put("b",true);
        try {
            // runner.getOperatorFactory().getOperator("||").setErrorInfo("$1 或 $2 ");
            runner.addOperatorWithAlias("或者","&&","$1 或者 $2");
            Object  result =  runner.execute(rule, context, errorInfo, true, false);
            System.out.println(result);
            for(String error : errorInfo){
                System.out.println(error);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
```
