### ISSUE TITLE
示例报错 for 中定义多个变量

### ISSUE THREAD

**Issue by siqiniao** [alibaba/QLExpress#91]
n=10;
for(sum=0,i=0;i<n;i++){
       sum=sum+i;
}
return sum;

Exception in thread "main" com.ql.util.express.exception.QLCompileException: 还有单词没有完成语法匹配：4[for:line=2,col=1] 之后的单词 
n=10;
for(sum=0,i=0;i<n;i++){
sum=sum+i;
}
return sum;
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:401)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:355)
	at com.ql.util.express.parse.ExpressParse.parse(ExpressParse.java:329)
	at com.ql.util.express.ExpressRunner.parseInstructionSet(ExpressRunner.java:700)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:604)
	at com.ql.util.express.ExpressRunner.execute(ExpressRunner.java:581)
	at test.SongTest.main(SongTest.java:32)

**Comment by nkcoder** [comment]
我也发现执行不了，换一种形式：

`n=10; sum=0;
for(i=0;i<n;i++) {
    sum=sum+i;
}
return sum;`
